import { chromium } from 'playwright';
const b = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 640, height: 360 } });
p.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') console.log('[' + m.type() + ']', m.text().slice(0, 400)); });
p.on('pageerror', (e) => console.log('[pageerror]', e.message));
await p.addInitScript(() => localStorage.setItem('pz.settings.v1', '{"graphics":"mittel","fpsCap":3,"firstRun":false}'));
const t0 = Date.now();
const log = (s) => console.log(((Date.now() - t0) / 1000).toFixed(0) + 's', s);
await p.goto('http://localhost:8913/');
await p.waitForSelector('.menu-foot', { timeout: 240000 }); log('Menü');
const clickText = (t) => p.evaluate((t) => { const b = [...document.querySelectorAll('button')].find((x) => x.textContent.trim() === t); if (!b) return false; b.click(); return true; }, t);
const until = async (fn, ms = 200000) => { const t1 = Date.now(); while (Date.now() - t1 < ms) { if (await fn()) return true; await p.waitForTimeout(500); } return false; };
log(await until(() => clickText('Einzelspieler')) ? 'Einzelspieler' : 'kein Einzelspieler-Knopf');
log(await until(() => p.evaluate(() => { const b = document.querySelectorAll('.slot')[1]?.querySelector('button'); if (!b) return false; b.click(); return true; })) ? 'Slot' : 'kein Slot');
log(await until(() => p.evaluate(() => { const i = document.querySelector('input[placeholder^="Name"]'); if (!i) return false; i.value = 'Aren'; i.dispatchEvent(new Event('input')); return true; })) ? 'Name' : 'kein Namensfeld');
log(await until(() => clickText('Erwachen')) ? 'Erwachen' : 'kein Erwachen');
log(await until(() => p.evaluate(() => !!window.__pz?.local)) ? 'im Spiel' : 'nicht im Spiel');
await p.waitForTimeout(5000);
log('fertig');
await b.close();
