export interface AchievementDef { id: string; name: string; desc: string; icon: string; shards?: number; hidden?: boolean }

const list: AchievementDef[] = [
  { id: 'first_blood', name: 'Erste Narbe', desc: 'Besiege deinen ersten Gegner.', icon: '⚔' },
  { id: 'hunter100', name: 'Hundert Schatten', desc: 'Besiege 100 Gegner.', icon: '💀', shards: 2 },
  { id: 'bestiary', name: 'Naturkundler', desc: 'Begegne 8 verschiedenen Kreaturenarten.', icon: '📖', shards: 2 },
  { id: 'echo_hunter', name: 'Schweigen', desc: 'Bringe 10 Nachhalle zum Schweigen.', icon: '🔇', shards: 1 },
  { id: 'splinterlord', name: 'Fürstensturz', desc: 'Besiege den Splitterfürsten.', icon: '👑', shards: 3 },
  { id: 'tide_warden', name: 'Wächter der Gezeiten', desc: 'Besiege den Gezeitenwächter.', icon: '🌊', shards: 3 },
  { id: 'cartographer', name: 'Kartograf', desc: 'Entdecke alle Orte des Tals.', icon: '🗺', shards: 2 },
  { id: 'treasure', name: 'Schatzsucher', desc: 'Öffne alle versteckten Truhen der Oberwelt.', icon: '💰', shards: 2 },
  { id: 'chests10', name: 'Langfinger', desc: 'Öffne 10 Truhen.', icon: '🗝' },
  { id: 'viewpoint', name: 'Weitblick', desc: 'Genieße die Aussicht von der Rabenkanzel.', icon: '🦅' },
  { id: 'crafter', name: 'Handwerker', desc: 'Stelle 10 Gegenstände her.', icon: '🔨' },
  { id: 'masterwork', name: 'Meisterwerk', desc: 'Verbessere einen Gegenstand auf Stufe +5.', icon: '✨', shards: 2 },
  { id: 'level5', name: 'Erfahren', desc: 'Erreiche Stufe 5.', icon: '⭐' },
  { id: 'level10', name: 'Veteran', desc: 'Erreiche Stufe 10.', icon: '🌟', shards: 2 },
  { id: 'capstone', name: 'Meister eines Pfades', desc: 'Schalte eine Abschlussfähigkeit frei.', icon: '🏆', shards: 2 },
  { id: 'untouchable', name: 'Unberührbar', desc: '25 perfekte Ausweichmanöver.', icon: '💨' },
  { id: 'wall_of_iron', name: 'Eiserne Mauer', desc: '25 perfekte Blocks.', icon: '🛡' },
  { id: 'elementalist', name: 'Elementarist', desc: 'Löse eine Elementarkombination aus.', icon: '☯' },
  { id: 'gleichklang', name: 'Gleichklang', desc: 'Entlade eine gemeinsame Resonanz.', icon: '🎵' },
  { id: 'savior', name: 'Retter', desc: 'Belebe einen gefallenen Mitspieler wieder.', icon: '❤' },
  { id: 'twin_seal', name: 'Zwei Herzen, ein Siegel', desc: 'Öffne das Zwillingssiegel gemeinsam mit einem Mitspieler.', icon: '🔗' },
  { id: 'hollow_captain', name: 'Der Hauptmann ruht', desc: 'Besiege den Hohlen Hauptmann.', icon: '⚰', shards: 4 },
  { id: 'solo_captain', name: 'Allein im Glas', desc: 'Besiege den Hohlen Hauptmann ohne Gruppe.', icon: '🗡', shards: 3 },
  { id: 'story_done', name: 'Nummer Null', desc: 'Schließe die Hauptgeschichte ab.', icon: '⦻', shards: 5 },
  { id: 'number_zero', name: 'Wer bin ich?', desc: 'Erfahre die Wahrheit über deine Herkunft.', icon: '❓', hidden: true },
  { id: 'helping_hand', name: 'Helfende Hand', desc: 'Schließe 5 Nebenquests ab.', icon: '🤲', shards: 2 },
  { id: 'three_voices', name: 'Drei Stimmen', desc: 'Schließe die Aufträge aller drei Fraktionen ab.', icon: '⚖', shards: 2 },
  { id: 'truth', name: 'Die Wahrheit ans Licht', desc: 'Decke Aldric Veys Geheimnis auf und handle danach.', icon: '📜' },
  { id: 'touched', name: 'Kind des Lichts', desc: 'Erreiche eine Berührung von 80.', icon: '💠', hidden: true },
  { id: 'tide_secret', name: 'Der Gezeitenpfad', desc: 'Entschlüssle die drei Nullglyphen.', icon: '🌙', shards: 3, hidden: true },
  { id: 'legendary', name: 'Legende', desc: 'Finde einen legendären Gegenstand.', icon: '🔶' },
  { id: 'event_hero', name: 'Held des Tals', desc: 'Schließe 3 Welt-Ereignisse erfolgreich ab.', icon: '🎖', shards: 2 },
  { id: 'duelist', name: 'Duellant', desc: 'Gewinne ein freiwilliges Duell.', icon: '🤺' },
];

export const ACHIEVEMENTS: Record<string, AchievementDef> = Object.fromEntries(list.map((a) => [a.id, a]));
